### Project specific config ###
env:
  global:
    - ATOM_LINT_WITH_BUNDLED_NODE="false"

os:
  - osx

# Installed for linting the project
language: node_js
node_js: "6"

install:
  - npm install -g sass-lint

### Generic setup follows ###
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
